format = "\\[$username$hostname|$time|$git_branch$git_commit$git_status\\] $directory\n$character"
[directory]
format = "[$path]($style)"
style = "'fg:#e3e5e5 bg:#769ff0'"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "$symbol$branch"

[git_commit]
format = "\\($hash$tag\\)"
only_detached = false

[git_status]
format = "[[($modified$untracked$ahead_behind)](fg:#769ff0 bg:#394260)]($style)"
style = "bg:#394260"

[hostname]
format = "@$hostname"

[time]
disabled = false
format = "[$time]($style)"
style = "fg:#e3e5e5 bg:#769ff0"

[username]
format = "[$user]($style)"
show_always = true
